name: Build and Push Docker image with Latest Release

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get latest release version from GitHub API
      id: latest-version
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/TeaOSLab/EdgeAdmin/releases/latest | jq -r .tag_name)
        echo "Latest version is $LATEST_VERSION"
        echo "::set-output name=VERSION::$LATEST_VERSION"

    - name: Build Docker Image
      run: |
        docker build --build-arg VERSION=${{ steps.latest-version.outputs.VERSION }} -t vpsss/edge-admin:${{ steps.latest-version.outputs.VERSION }} -t vpsss/edge-admin:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker push vpsss/edge-admin:${{ steps.latest-version.outputs.VERSION }}
        docker push vpsss/edge-admin:latest
